/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jhotdraw.revisionhistory;

import java.awt.BorderLayout;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import org.jhotdraw.draw.Drawing;

/**
 *
 * @author emilfrisk
 */
public class RevisionView extends javax.swing.JPanel {

    JFrame frame;
    public DefaultListModel listModel;
    public RevisionController revisionController;

    /**
     * Creates new form RevisionView
     */
    public RevisionView() {
        initComponents();
        listModel = (DefaultListModel) revisionList.getModel();
	listModel.addElement("Hallo");
    }

    public void setup() {
        frame = new JFrame();
        frame.setLayout(new BorderLayout());
        final RevisionView p = new RevisionView();
        frame.add(p, BorderLayout.CENTER);
	frame.pack();

	for (Drawing d: revisionController.revisions){
		p.listModel.addElement(d);
	}

    }

    @Override
    public void setVisible(boolean visible) {
        frame.setVisible(visible);
    }

    public void setRevisionController(RevisionController revisionController) {
        this.revisionController = revisionController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                revisionList = new javax.swing.JList();

                revisionList.setModel(new DefaultListModel());
                jScrollPane1.setViewportView(revisionList);

                org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JList revisionList;
        // End of variables declaration//GEN-END:variables
}
